TRUNCATE TABLE public.email RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.contact RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.action RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.address RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.document_binary_data RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.document_metadata RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.message RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.telephone RESTART IDENTITY CASCADE;
